exec-once = nm-applet
exec-once = blueman-applet
exec-once = systemctl --user start hyprpolkitagent 
exec-once = swayosd-server
exec-once = hyprpaper
exec-once = quickshell

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show run

monitor=eDP-1,1920x1080,0x0,1.3333333

bind = $mainMod, T, exec, $terminal 
bind = $mainMod, Q, killactive
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, togglefloating,
bind = $mainMod, R, exec, $menu

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bindel = ,XF86AudioRaiseVolume, exec, swayosd-client $monitor --output-volume 5 && pw-play /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
bindel = ,XF86AudioLowerVolume, exec, swayosd-client $monitor --output-volume -5 && pw-play /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
bindel = ,XF86AudioMute, exec, swayosd-client $monitor --output-volume mute-toggle
bindel = ,XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle
bindel = ,XF86MonBrightnessUp, exec, swayosd-client $monitor --brightness raise
bindel = ,XF86MonBrightnessDown, exec, swayosd-client $monitor --brightness lower

bind = $mainMod, L, exec, hyprlock

# Hyprshot
bind = , PRINT, exec, hyprshot -m output
bind = $mainMod, PRINT, exec, hyprshot -m window
bind = $mainMod $shiftMod, PRINT, exec, hyprshot -m region

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto

input {
    touchpad {
        natural_scroll = true
    }
}